src/main/java/org/atlasapi/query/v2/ContentFeedController.java

These would never be uploaded to YouView anyway, and break
since later code relies on them being present

Filter broadcasts without crids from controller output

---

src/main/java/org/atlasapi/remotesite/bbc/nitro/ContentUpdatingNitroBroadcastHandler.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/LocalOrRemoteNitroFetcher.java

(rather than assuming that the existing Content is being modified (which isn't always true).)

Actually use the returned value from the ContentMerger

---

src/main/java/org/atlasapi/output/simple/DescribedModelSimplifier.java
src/main/java/org/atlasapi/output/simple/ItemModelSimplifier.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/BaseNitroItemExtractor.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroContentExtractor.java
src/test/java/org/atlasapi/output/simple/ItemModelSimplifierTest.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractorTest.java

Currently storing version PIDs from Nitro.

Store and output aliases on Version

---

src/main/java/org/atlasapi/remotesite/knowledgemotion/KnowledgeMotionUpdater.java

stop tasks from setting activelyPublished to false for all Knowledgemotion publishers

Fix Knowledgemotion ingest task

---

src/main/java/org/atlasapi/query/QueryWebModule.java
src/main/java/org/atlasapi/query/v2/ContentWriteController.java

This will also ensure that schedule update events are created,
which means that deer schedule stores will be updated

Maintain schedules for POSTed items

---

src/main/java/org/atlasapi/remotesite/btvod/BtVodItemWriter.java
src/main/java/org/atlasapi/remotesite/btvod/TitleSanitiser.java
src/test/java/org/atlasapi/remotesite/btvod/TitleSanitiserTest.java

Make sure sanitisation happens on all types, consistently.

Move title sanitisation to a single place

---

src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentExtractor.java
src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentHandler.java
src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxItem.java
src/test/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentExtractorTest.java

We now support different payment methods - rental, purchase
and subscription.

Create multiple locations and encodings

---

src/main/java/org/atlasapi/equiv/results/combining/RequiredScoreFilteringCombiner.java

Previously we were considering only the first
required score that was found, rather than any.

Consider all required scores

---

src/main/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorer.java
src/test/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorerTest.java

These are especially common in football match titles

Handle abbreviated words

---

src/main/java/org/atlasapi/equiv/EquivModule.java

Now needs a negative score for big hierarchy
mismatches.

Configure hierarchy matching scorer

---

src/main/java/org/atlasapi/remotesite/btvod/BtVodItemExtractor.java
src/main/java/org/atlasapi/remotesite/btvod/TitleSanitiser.java
src/test/java/org/atlasapi/remotesite/btvod/BtVodItemExtractorTest.java
src/test/java/org/atlasapi/remotesite/btvod/TitleSanitiserTest.java

- Moved all title extracting logic to TitleSanitiser.java
- Changed title extracting logic to strip " - HD" postfix before any other step
- Applied episode title extracting logic to films

Extract BT TVE VOD film title using existing pattern matching logic

---

src/main/java/org/atlasapi/remotesite/btvod/TitleSanitiser.java
src/test/java/org/atlasapi/remotesite/btvod/TitleSanitiserTest.java

Tidy up existing collection rules pulling them into
extraction patterns rather than replacement patterns, too.

Add collection title format

---

src/main/java/org/atlasapi/remotesite/btvod/AbstractBtVodSeriesExtractor.java
src/main/java/org/atlasapi/remotesite/btvod/BrandDescriptionUpdater.java
src/main/java/org/atlasapi/remotesite/btvod/BtVodBrandProvider.java
src/test/java/org/atlasapi/remotesite/btvod/BrandDescriptionUpdaterTest.java
src/test/java/org/atlasapi/remotesite/btvod/BtVodBrandProviderTest.java

- Also get the first non-null description from series

Ingest long description for TVE brands from their series

---

src/main/java/org/atlasapi/input/ContentModelTransformer.java
src/main/java/org/atlasapi/query/QueryWebModule.java
src/main/java/org/atlasapi/query/v2/ContentWriteController.java
src/test/java/org/atlasapi/input/ItemModelTransformerTest.java

- ModelContentTransformer - changes to handle event refs

Event Refs - not ready for merge yet, for comments please!

---

src/test/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractorTest.java

Revert "deleted imports that failed test"

---

src/main/java/org/atlasapi/remotesite/ContentMerger.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractor.java
src/test/java/org/atlasapi/remotesite/ContentMergerTest.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractorTest.java

Revert "Ingest release date from Nitro"

---

src/main/java/org/atlasapi/remotesite/btvod/BtVodDescribedFieldsExtractor.java

Also use a scale from 0-100, with 0 being highest priority

Always set a priority

---

src/main/java/org/atlasapi/input/DescribedModelTransformer.java
src/main/java/org/atlasapi/input/ItemModelTransformer.java
src/main/java/org/atlasapi/query/v2/ContentWriteController.java
src/test/java/org/atlasapi/input/ItemModelTransformerTest.java
src/test/java/org/atlasapi/output/simple/ItemModelSimplifierTest.java

Revert "Adding fields to be transformed and simplified for episode and location"

---

src/main/java/org/atlasapi/input/DescribedModelTransformer.java
src/main/java/org/atlasapi/input/ItemModelTransformer.java
src/main/java/org/atlasapi/query/v2/ContentWriteController.java
src/test/java/org/atlasapi/input/ItemModelTransformerTest.java
src/test/java/org/atlasapi/output/simple/ItemModelSimplifierTest.java

Revert "Revert "Adding fields to be transformed and simplified for episode and location""

---

src/main/java/org/atlasapi/equiv/query/MergeOnOutputQueryExecutor.java
src/main/java/org/atlasapi/query/QueryModule.java
src/main/java/org/atlasapi/query/content/ApplicationConfigurationQueryExecutor.java
src/main/java/org/atlasapi/query/content/CurieResolvingQueryExecutor.java
src/main/java/org/atlasapi/query/content/EventResolvingQueryExecutor.java
src/main/java/org/atlasapi/query/content/FilterActivelyPublishedOnlyQueryExecutor.java
src/main/java/org/atlasapi/query/content/FilterScheduleOnlyQueryExecutor.java
src/main/java/org/atlasapi/query/content/LookupResolvingQueryExecutor.java
src/main/java/org/atlasapi/query/content/UriFetchingQueryExecutor.java
src/main/java/org/atlasapi/query/v2/QueryController.java

(cherry picked from commit 6254a11)

Query content with event refs

---

src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfUpdateTask.java
src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesVideoEpisodeExtractor.java

1. Check bimap fo existing keys before writing
2. Duration extracting is optional now

Itunes fixed

---

src/main/java/org/atlasapi/equiv/generators/ContentTitleScorer.java
src/test/java/org/atlasapi/equiv/generators/ContentTitleScorerTest.java

If titles match exactly, boost them to have them win
over sequence matches.

Boost exact title matches

---

src/main/java/org/atlasapi/output/simple/ChannelSimplifier.java
src/main/java/org/atlasapi/remotesite/bt/channels/BtChannelDataUpdater.java
src/test/java/org/atlasapi/remotesite/bt/channels/GsonBtMpxClientTest.java

update to output advertiseFrom field in endpoint and tests for different env

---

src/main/java/org/atlasapi/remotesite/pa/PaModule.java

Maps PA key in features xml file to new Freeview Features Publisher.

Add mapping to new Freeview Featureset

---

src/main/java/org/atlasapi/remotesite/itunes/epf/EpfDataSet.java
src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfPricingSource.java
src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfUpdateTask.java
src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesPricingLocationExtractor.java
src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesVideoEpisodeExtractor.java
src/main/java/org/atlasapi/remotesite/itunes/epf/model/EpfPricing.java
src/main/java/org/atlasapi/remotesite/itunes/epf/model/EpfStorefront.java
src/test/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfUpdateTaskTest.java
src/test/java/org/atlasapi/remotesite/itunes/epf/ItunesPricingLocationExtractorTest.java

Itunes was using flat itunes feed for ingesting Location. This PR changes it to use relational feed only

Converted using pricing from flat feed to relational feed

---

src/main/java/org/atlasapi/equiv/EquivModule.java
src/main/java/org/atlasapi/equiv/results/filters/FilmFilter.java
src/test/java/org/atlasapi/equiv/results/filters/FilmFilterTest.java

Filter films with different release years

---

src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
src/test/java/org/atlasapi/remotesite/pa/PaProgrammeProcessorTest.java

- Because Welsh channels have Welsh title and descriptions we ignore
them unless we don't have any existing values for that item. An
inverted condition meant we were only grabbing titles and descriptions
for Welsh channels instead.
- Refactored logic for handling Welsh title and descriptions to
eliminate code duplication
- Refactored logic for adding common details to items to eliminate
code duplication
- Add test for ingesting broadcast

Fix logic that ignores descriptions for Welsh channels

---

src/main/java/org/atlasapi/equiv/EquivTaskModule.java

Revert "running equivalence tasks on startup"

---

src/main/java/org/atlasapi/input/ItemModelTransformer.java
src/main/java/org/atlasapi/query/v2/ContentWriteController.java
src/test/java/org/atlasapi/input/ItemModelTransformerTest.java

*duration
*countries of origin
*year
*series and episode number for episodes

Missing fields in post API

---

src/main/java/org/atlasapi/input/ItemModelTransformer.java
src/test/java/org/atlasapi/input/ItemModelTransformerTest.java

- Pull restriction transformation to setFields(...) since
restrictions could exist in both broadcasts and locations and are a
field of the version in the complex model
- In the process fix a bug where we were creating a new version per
location, setting its restriction and then discarded it
- Remove special broadcast type handling in createOutput(...) since
broadcasts are handled generically in setFields(...) anyway

Fix bug where we were ignoring restrictions on locations

---

src/main/java/org/atlasapi/equiv/EquivTaskModule.java

Equiv updater for EBMS VF data
Added it before in a past PR but it seems to have gotten removed.
https://github.com/atlasapi/atlas/pull/867/files

Adding equivalence updater

---

src/main/java/org/atlasapi/remotesite/ContentMerger.java
src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentExtractor.java
src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentWritingItemProcessor.java
src/test/java/org/atlasapi/remotesite/ContentMergerTest.java
src/test/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentWritingItemProcessorTest.java
src/test/resources/org/atlasapi/remotesite/amazonunbox/hierarchy.xml

2.Change to contentmerger
3.Ingest title as short description

1.Deduplicate content based on title/episode/series/type

---

src/main/java/org/atlasapi/remotesite/itunes/ItunesModule.java
src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfUpdateTask.java
src/test/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfUpdateTaskTest.java

-Ingest episodes only if it has location available from UK
-Deactivating existing items that were not ingested
-Test using mockito rather than jmock in itunes
-reformatting

tunes ingester changes

---

src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentWritingItemProcessor.java

-Previsouly episodes and series could have parentRefs to content that will be deactivated. Now before writing content in we change contentRefs of content of the same brand to one common brand.

Changing links to parentRefs after extracting content

---

src/main/resources/config/environment.properties

as we need to deactivate bunch of content after deduping

changing unbox missingContentPercentage 

---

src/main/java/org/atlasapi/remotesite/five/FiveUpdater.java

to avoid timing outs trying to fetch all data

Added pagination to Five updater 

---

src/main/java/org/atlasapi/equiv/EquivModule.java
src/main/java/org/atlasapi/equiv/generators/EquivalenceGenerators.java
src/main/java/org/atlasapi/equiv/update/ContentEquivalenceUpdater.java
src/test/java/org/atlasapi/equiv/generators/EquivalenceGeneratorsTest.java

Add exclusion of content equivalence based on provided uris

Equivalence exclusion

---

README.md
src/main/java/org/atlasapi/remotesite/rt/RtFilmProcessor.java
src/main/resources/config/environment.properties

Please see https://jira.metabroadcast.com/browse/MBST-14273

Radiotimes scores reviews

---

src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroClipsAdapter.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroContentAdapter.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/LazyNitroEpisodeExtractor.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/LocalOrRemoteNitroFetcher.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/NitroContentAdapter.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/OffScheduleContentIngestTask.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/PaginatedNitroItemSources.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/PaginatedProgrammeRequest.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/PidUpdateController.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroContentAdapterTest.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/PaginatedProgrammeRequestTest.java

This has been done to reduce the heap overhead of off schedule ingest.

Adding Glycerin query executor that implements Iterable

---

src/main/java/org/atlasapi/remotesite/bbc/nitro/PaginatedProgrammeRequest.java

bug fix for programme pagination

bug fix un the programme pagination logic

---

src/main/java/org/atlasapi/equiv/EquivTaskModule.java

- Those YV jobs run at 2130 in the evening so to ensure we have at
least +7 day coverage from the next day onwards we will run them
for +8 days

Run YV schedule equivalence jobs for +8 days in the future

---

src/main/java/org/atlasapi/system/ContentPurgeWebModule.java
src/main/java/org/atlasapi/system/UnpublishContentController.java

To use:
curl -i -XPOST 'http://localhost:8080/system/content/unpublish/{:id}'
Note:
This endpoint does not recursively unpublish versions.   TBD if required

MBST-15461: Content unpublish endpoint:

---

src/main/java/org/atlasapi/output/AtlasErrorSummary.java
src/main/java/org/atlasapi/output/MissingApplicationOwlAccessRoleException.java
src/main/java/org/atlasapi/query/v2/BaseController.java
src/main/java/org/atlasapi/query/v2/ContentGroupController.java
src/main/java/org/atlasapi/query/v2/ProductController.java
src/main/java/org/atlasapi/query/v2/QueryController.java
src/main/java/org/atlasapi/query/v2/TopicController.java

- Access that does not require an API key remains permitted

Only allow read access to the API for keys with OWL_ACCESS role

---

src/main/java/org/atlasapi/system/UnpublishContentController.java

MBST-15461: Unpublisher endpoint: mandate the user specifies a publisher

---

src/main/java/org/atlasapi/equiv/generators/FilmEquivalenceGenerator.java

Avoid nullpointer exception comparing years

---

src/main/java/org/atlasapi/input/ChannelModelTransformer.java
src/main/java/org/atlasapi/input/DefaultGsonModelReader.java
src/main/java/org/atlasapi/input/ImageModelTranslator.java
src/main/java/org/atlasapi/query/QueryExecutorModule.java
src/main/java/org/atlasapi/query/QueryWebModule.java
src/main/java/org/atlasapi/query/v2/ChannelWriteController.java
src/main/java/org/atlasapi/query/v2/QueryController.java
src/test/java/org/atlasapi/input/GsonDescriptionReaderTest.java

Removed channel controller from query web module
Adding Request Mapping annotation to postChannel method in channel write controller

Addressing pull-request comments

---

src/main/java/org/atlasapi/input/ChannelModelTransformer.java
src/main/java/org/atlasapi/input/DefaultGsonModelReader.java
src/main/java/org/atlasapi/input/ImageModelTranslator.java
src/main/java/org/atlasapi/query/QueryExecutorModule.java
src/main/java/org/atlasapi/query/QueryWebModule.java
src/main/java/org/atlasapi/query/v2/ChannelController.java
src/main/java/org/atlasapi/query/v2/ChannelWriteController.java
src/main/java/org/atlasapi/query/v2/QueryController.java
src/test/java/org/atlasapi/input/ChannelModelTransformerTest.java
src/test/java/org/atlasapi/input/GsonDescriptionReaderTest.java
src/test/java/org/atlasapi/input/ImageModelTranslatorTest.java

+  Implemented channel translator from simple model to complex model.

Adding channel POST endpoint.

---

pom.xml
src/main/java/org/atlasapi/input/DefaultJacksonModelReader.java
src/main/java/org/atlasapi/input/JacksonModelReader.java
src/main/java/org/atlasapi/output/AtlasErrorSummary.java
src/main/java/org/atlasapi/output/JsonTranslator.java
src/main/java/org/atlasapi/output/exceptions/ForbiddenException.java
src/main/java/org/atlasapi/output/exceptions/UnauthorizedException.java
src/main/java/org/atlasapi/query/QueryExecutorModule.java
src/main/java/org/atlasapi/query/QueryWebModule.java
src/main/java/org/atlasapi/query/v2/ChannelWriteController.java
src/main/java/org/atlasapi/query/v2/ContentWriteController.java
src/main/java/org/atlasapi/query/v2/PeopleWriteController.java
src/main/java/org/atlasapi/query/v2/TopicWriteController.java
src/test/java/org/atlasapi/input/DefaultJacksonModelReaderTest.java
src/test/java/org/atlasapi/output/AtlasErrorSummaryTest.java
src/test/java/org/atlasapi/query/v2/ContentWriteControllerTest.java
src/test/java/org/atlasapi/query/v2/PeopleControllerTest.java

- changed the deserialser to use jackson
- added new exceptions to the current exception mapper logic
- using hibernate validator to check if fields are not null
- changed all write controller to use jackson translator

wrote different exceptions for different error cases

---

src/main/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorer.java
src/test/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorerTest.java

2. With accents En équilibre
3. With postfixes like (Unrated)

1. Dealing with spacing like HouseBusters vs House Busters

---

src/main/java/org/atlasapi/query/v2/ScheduleController.java

- This is caused by `now` being evaluated twice. Once for the `from`
parameter and once for the `to`. If `now` milliseconds change
between the two evaluations then `from=now&to=now.plus.24h` will
resolve to an interval that is 24hrs + 1ms long which will then
trigger the check that schedule calls are not longer than 24hrs and
fail the call

Fix bug where `from=now&to=now.plus.24h` resolves to 24hrs + 1ms

---

src/main/java/org/atlasapi/remotesite/wikipedia/wikiparsers/SwebleHelper.java
src/test/java/org/atlasapi/remotesite/wikipedia/FootballTeamsExtractionTest.java

- Wikipedia API has started rejecting HTTP calls and forcing use of
HTTPS

Change Wikipedia API URL to HTTPS

---

src/main/java/org/atlasapi/equiv/results/combining/NullScoreAwareAveragingCombiner.java
src/main/java/org/atlasapi/equiv/scorers/BaseBroadcastItemScorer.java
src/main/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorer.java
src/test/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorerTest.java
src/test/java/org/atlasapi/equiv/scorers/TitleSubsetBroadcastItemScorerTest.java

1.don't equivalate sports channels based on titles

---

src/main/java/org/atlasapi/equiv/update/tasks/ScheduleEquivalenceUpdateTask.java
src/test/java/org/atlasapi/equiv/update/tasks/ScheduleEquivalenceUpdateTaskTest.java

Revert "when schedule equivalence run we overwrite previous equivalences, now…"

---

src/main/java/org/atlasapi/equiv/update/tasks/ScheduleEquivalenceUpdateTask.java
src/test/java/org/atlasapi/equiv/update/tasks/ScheduleEquivalenceUpdateTaskTest.java

Revert "Revert "when schedule equivalence run we overwrite previous equivalences, now…""

---

src/main/java/org/atlasapi/equiv/generators/BroadcastMatchingItemEquivalenceGenerator.java

to allow match on endtime more flexibly

easing rules for matching on broadcast

---

src/main/java/org/atlasapi/equiv/EquivTaskModule.java
src/main/java/org/atlasapi/query/QueryExecutorModule.java

Add persistent retry policy for Atlas Owl Kafka consumers

---

src/main/java/org/atlasapi/query/v2/ContentWriteController.java

Include a leading slash for request mapping value

Fix incorrect request path

---

src/main/java/org/atlasapi/equiv/EquivModule.java
src/main/java/org/atlasapi/equiv/scorers/DescriptionMatchingScorer.java
src/test/java/org/atlasapi/equiv/scorers/DescriptionMatchingScorerTest.java

- New scorer matches description to description
- Helps matching content with missing fields
- Potentially useful for sport where titles often mismatch

Add equiv scorer for matching descriptions

---

src/main/java/org/atlasapi/equiv/scorers/DescriptionTitleMatchingScorer.java

in description title scorer
also changed the ordering for how common words are filtered out

added peppa and pig to list of common words to filter out 

---

src/main/java/org/atlasapi/equiv/scorers/ContainerHierarchyMatchingScorer.java

- This is causing a lot of errors in the processing-equiv logs

Fix missing string formatting parameter

---

src/main/java/org/atlasapi/query/content/schedule/ManualScheduleUpdateController.java

Revert "update constructor for changes in atlas-persistence"

---

src/main/java/org/atlasapi/remotesite/pa/PaSingleDateUpdatingController.java

Disable the PA single day updater due to data consistency bugs

---

src/main/java/org/atlasapi/query/content/merge/BroadcastMerger.java
src/test/java/org/atlasapi/query/content/merge/BroadcastMergerTest.java

with different channel URI + test

fixed logic to update an existing broadcast 

---

src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java

Previously when constructing the uri we would failover to ProgId if the
rtFilmIdentifier was missing but still write to the same namespace. To
avoid creating duplicates we have to replicate this old behavior and
use the rtFilmIdentifier for resolution when its available

When resolving films use the rtFilmIdentifier and failover to progId

---

src/main/resources/config/environments/prod.properties

- They should be off by default and only enabled on the appropriate
boxes

Ensure updaters/feeds are only explicitly enabled

---

src/main/java/org/atlasapi/equiv/scorers/DescriptionMatchingScorer.java
src/test/java/org/atlasapi/equiv/scorers/DescriptionMatchingScorerTest.java

Simple number change and some refactoring for line length

increase proportion of capitalised words required for matching

---

src/main/java/org/atlasapi/input/BroadcastModelTransformer.java
src/main/java/org/atlasapi/output/simple/ItemModelSimplifier.java
src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
src/test/java/org/atlasapi/remotesite/pa/PaProgrammeProcessorTest.java

repeat flag rather than sharing repeat flag

Add revised repeat to model; Updated PA ingester to use the revised

---

src/main/java/org/atlasapi/query/QueryExecutorModule.java

- This prevents the services manager from printing a confusing error
to the logs which it does when it's given an empty list of services

Do not create a services manager if no services exist

---

src/main/java/org/atlasapi/equiv/results/filters/AbstractEquivalenceFilter.java
src/main/java/org/atlasapi/equiv/results/filters/ContainerHierarchyFilter.java
src/main/java/org/atlasapi/equiv/results/filters/DummyContainerFilter.java
src/main/java/org/atlasapi/equiv/results/filters/ExclusionListFilter.java
src/main/java/org/atlasapi/equiv/results/filters/FilmFilter.java
src/main/java/org/atlasapi/equiv/results/filters/MediaTypeFilter.java
src/main/java/org/atlasapi/equiv/results/filters/MinimumScoreFilter.java
src/main/java/org/atlasapi/equiv/results/filters/PublisherFilter.java
src/main/java/org/atlasapi/equiv/results/filters/SpecializationFilter.java
src/main/java/org/atlasapi/equiv/results/filters/UnpublishedContentFilter.java

toString override method extracted to the abstract filter class
There was a bit where I changed a boolean calculation - intellij simplified this in a click for me
The rest was line length and unused imports

naming extracted to abstract class and some code cleanup

---

src/main/java/org/atlasapi/remotesite/pa/PaModule.java

Revert "turned off PA channel ingest"

---

src/main/java/org/atlasapi/remotesite/bbc/nitro/LastUpdatedSettingContentWriter.java

Revert "added subtitle comparison for encodings"

---

src/main/java/org/atlasapi/remotesite/bbc/nitro/LastUpdatedSettingContentWriter.java

Revert "Revert "added subtitle comparison for encodings""

---

src/main/java/org/atlasapi/equiv/generators/BarbAliasEquivalenceGenerator.java
src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BarbItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/types/ItemEquivalenceUpdaterType.java

new barb generator based on alias matching created
equiv registry configured to use new barb sources

Make barb equivalence

---

src/main/resources/config/environment.properties

Revert "altering opta config to update panels for this year"

---

src/main/java/org/atlasapi/remotesite/bbc/nitro/ContentUpdatingNitroBroadcastHandler.java
src/main/java/org/atlasapi/remotesite/channel4/pmlsd/LastUpdatedSettingContentWriter.java
src/main/java/org/atlasapi/reporting/telescope/OwlTelescopeReporters.java

Fast pre-meeting merge. Telescope taskId is a placeholder. Unsure of implications.

C4 status service

---

src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxHttpFeedSupplier.java

Trying to clean the illegal characters contained in Amazon's xml

clean amazon xml

---

pom.xml
src/main/java/org/atlasapi/remotesite/rt/RtFilmFeedUpdater.java

the transform logic was less tangled than I thought, this should do it.

changed how rt film feed gets and transforms via http

---

src/main/java/org/atlasapi/equiv/generators/BarbAliasEquivalenceGeneratorAndScorer.java
src/test/java/org/atlasapi/equiv/generators/BarbAliasEquivalenceGeneratorAndScorerTest.java

This is due to BBC switching from today onwards to using
episode PIDs in place of version PIDs in txlogs, and
to using both in CDMF.
Jira: ENG-336

Barb equiv for episode pids

---

src/main/java/org/atlasapi/equiv/generators/BroadcastMatchingItemEquivalenceGeneratorAndScorer.java
src/main/java/org/atlasapi/equiv/generators/barb/BarbBbcActualTransmissionItemEquivalenceGeneratorAndScorer.java
src/main/java/org/atlasapi/equiv/scorers/BarbTitleMatchingItemScorer.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BbcTxlogsEfficientItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BbcTxlogsItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BarbBbcBroadcastItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/types/ItemEquivalenceUpdaterType.java

Copied the existing to a separate class and left a comment
about why it does not properly work at the moment.
It can be used in future if equiv is made unidirectional.

Moved to a more standard BbcTxlogsItemUpdaterProvider

---

src/main/java/org/atlasapi/equiv/EquivTaskModule.java
src/main/java/org/atlasapi/equiv/scorers/DescriptionMatchingScorer.java
src/main/java/org/atlasapi/equiv/scorers/DescriptionTitleMatchingScorer.java
src/main/java/org/atlasapi/equiv/update/handlers/providers/container/StandardNoEpisodeMatchingContainerHandlerProvider.java
src/main/java/org/atlasapi/equiv/update/handlers/types/ContainerEquivalenceHandlerType.java
src/main/java/org/atlasapi/equiv/update/updaters/configuration/DefaultConfiguration.java
src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/container/ImdbPaContainerUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/container/ImdbPaSeriesUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BarbItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BbcTxlogsItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BroadcastItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/ImdbPaItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/StandardItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/TxlogsItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/YouviewItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BarbBbcBroadcastItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/types/ContainerEquivalenceUpdaterType.java
src/main/java/org/atlasapi/equiv/update/updaters/types/ItemEquivalenceUpdaterType.java
src/test/java/org/atlasapi/equiv/scorers/DescriptionMatchingScorerTest.java
src/test/java/org/atlasapi/equiv/scorers/DescriptionTitleMatchingScorerTest.java

Initial equiv logic to be used for an upcoming demo.
Further changes will likely be made before the demo
and is all subject to change.

Imdb pa equiv for demoing

---

src/main/java/org/atlasapi/input/ContentModelTransformer.java
src/main/java/org/atlasapi/input/DescribedModelTransformer.java

Transform simple genres, ratings and certificates

---

src/main/java/org/atlasapi/equiv/generators/barb/BarbBroadcastMatchingItemEquivalenceGeneratorAndScorer.java

Bugfix
Logic was expecting only one publisher

Split candidate schedule by publisher in Barb BroadcastGenerator

---

src/main/java/org/atlasapi/equiv/generators/barb/BarbBbcActualTransmissionItemEquivalenceGeneratorAndScorer.java
src/main/java/org/atlasapi/equiv/generators/barb/BarbBbcRegionalTxlogItemEquivalenceGeneratorAndScorer.java
src/main/java/org/atlasapi/equiv/generators/barb/utils/BarbGeneratorUtils.java
src/main/java/org/atlasapi/equiv/update/metadata/EquivToTelescopeComponent.java
src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BarbItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BarbXItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BbcRegionalTxlogItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BbcTxlogsEfficientItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BbcTxlogsItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/TxlogsItemUpdaterProvider.java
src/main/java/org/atlasapi/equiv/update/updaters/types/ItemEquivalenceUpdaterType.java
src/test/java/org/atlasapi/equiv/generators/barb/BarbBbcRegionalTxlogItemEquivalenceGeneratorAndScorerTest.java
src/test/java/org/atlasapi/equiv/update/metadata/EquivToTelescopeResultTest.java

Equiv must require exactly same start time, end time, and title.
This is additional work for BBC for network linking, following on from all work done stemming from ENG-339,

Equiv between BBC regional txlogs (ENG-633)

---

src/main/java/org/atlasapi/equiv/generators/barb/BarbBbcRegionalTxlogItemEquivalenceGeneratorAndScorer.java
src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BbcRegionalTxlogItemUpdaterProvider.java
src/test/java/org/atlasapi/equiv/generators/barb/BarbBbcRegionalTxlogItemEquivalenceGeneratorAndScorerTest.java

Agreed with BBC to use 30s for now and revise if necessary

Make BarbBbcRegionalTxlog broadcast equiv flexible (ENG-633)

---

src/main/java/org/atlasapi/query/content/merge/ContentMerger.java

Allow genres to be updated for pre-existing content

---

src/main/java/org/atlasapi/query/content/merge/ContentMerger.java
src/main/java/org/atlasapi/query/content/merge/ItemMerger.java

IMDb re-ingest was not updating them. ENG-711

Allow updates of ratings + certificates thru owl-api

---

pom.xml
src/main/java/org/atlasapi/equiv/EquivalenceBreaker.java
src/main/java/org/atlasapi/equiv/LookupRefUpdateTask.java
src/main/java/org/atlasapi/equiv/results/www/EquivGraphController.java
src/main/java/org/atlasapi/messaging/ContentEquivalenceAssertionMessenger.java
src/main/java/org/atlasapi/query/v2/ContentWriteController.java
src/main/java/org/atlasapi/remotesite/pa/deletes/ExistingItemUnPublisher.java
src/main/java/org/atlasapi/remotesite/youview/YouViewEquivalenceBreaker.java
src/main/java/org/atlasapi/system/UnpublishContentController.java
src/test/java/org/atlasapi/equiv/EquivalenceBreakerTest.java
src/test/java/org/atlasapi/equiv/LookupRefUpdateTaskTest.java
src/test/java/org/atlasapi/equiv/generators/BarbAliasEquivalenceGeneratorAndScorerTest.java
src/test/java/org/atlasapi/equiv/messengers/QueueingEquivalenceResultMessengerTest.java
src/test/java/org/atlasapi/query/content/LookupResolvingQueryExecutorTest.java
src/test/java/org/atlasapi/query/v2/ContentWriteControllerTest.java
src/test/java/org/atlasapi/remotesite/pa/deletes/ExistingItemUnPublisherTest.java
src/test/java/org/atlasapi/remotesite/youview/YouViewEquivalenceBreakerTest.java

Changes to accommodate LookupEntry restructure.

(ENG-741) Asymmetric equivalence

---

src/main/java/org/atlasapi/equiv/handlers/LookupWritingEquivalenceHandler.java
src/test/java/org/atlasapi/equiv/handlers/LookupWritingEquivalenceHandlerTest.java

This seems to have been in place to prevent
equivalence being broken on links which had
recently been known to not be outdated,
back when equivlance was not asymmetric.
Now that equivlance is asymmetric we can
remove this logic since such links will not be
removed anyway since they will be kept
as incoming links.

(ENG-761) Remove old equiv symmetry hack

---

pom.xml
src/main/java/org/atlasapi/AtlasModule.java
src/main/java/org/atlasapi/equiv/DataBackpopulationModule.java
src/main/java/org/atlasapi/equiv/LookupRefUpdateTask.java
src/main/java/org/atlasapi/query/QueryModule.java
src/test/java/org/atlasapi/equiv/ChildRefUpdateTaskTest.java
src/test/java/org/atlasapi/equiv/LookupRefUpdateTaskTest.java
src/test/java/org/atlasapi/equiv/PersonRefUpdateTaskTest.java
src/test/java/org/atlasapi/remotesite/pa/PaBaseProgrammeUpdaterTest.java

Changed MongoLookupEntryStore constructor usage to use the modified constructor.

Create new mongo client bean

---

pom.xml
src/main/java/org/atlasapi/input/ItemModelTransformer.java
src/main/java/org/atlasapi/output/simple/ItemModelSimplifier.java
src/main/java/org/atlasapi/query/content/merge/VersionMerger.java

For JustWatch deeplinks: ENG-805

Add providers for locations (justwatch deeplinks)

---

src/main/java/org/atlasapi/ConfigurableAnnotationWebApplicationContext.java
src/main/java/org/atlasapi/ThematicLabels.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/BbcNitroModule.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroClipsAdapter.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroContentAdapter.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/BaseNitroItemExtractor.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroBrandExtractor.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroClipExtractor.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroContentExtractor.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractor.java
src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroSeriesExtractor.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroContentAdapterTest.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/PaginatedNitroItemSourcesTest.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroBrandExtractorTest.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractorTest.java
src/test/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroSeriesExtractorTest.java

Move thematic labels to a class with static accessors and caching.

Improve implementation of thematic labels

---

src/main/java/org/atlasapi/remotesite/pa/channels/PaChannelDataHandler.java

Update the RadioTimes channel group with new channels from PA ingest.

RadioTimes Channel Group Automation

---

src/main/java/org/atlasapi/input/ChannelModelTransformer.java
src/main/java/org/atlasapi/query/v2/ChannelController.java
src/main/java/org/atlasapi/query/v2/ChannelWriteExecutor.java
src/test/java/org/atlasapi/input/ChannelModelTransformerTest.java

This is to allow merging the channel logos on channels created through the api in the YouView JSON ingest (ingest-youview) with the custom logos set on the channels by BT using the channel logo tool.

Merge images in channels api

---

pom.xml
src/main/java/org/atlasapi/input/BrandModelTransformer.java
src/main/java/org/atlasapi/input/EncodingModelTransformer.java
src/main/java/org/atlasapi/input/ItemModelTransformer.java
src/main/java/org/atlasapi/input/RestrictionModelTransformer.java
src/main/java/org/atlasapi/input/SeriesModelTransformer.java

Refactored some related code from the ItemModelTransformer
into separate classes to prevent code duplication.

Added location transforming for brand and series in simple model

---

src/main/java/org/atlasapi/remotesite/bbc/ion/BbcIonServices.java

This should allow us to ingest content from this masterbrand.

adds masterbrand for bbc-wales
