atlasapi/atlas

- src/main/java/org/atlasapi/remotesite/btvod/BtVodContentGroupUpdater.java
- src/main/java/org/atlasapi/remotesite/btvod/portal/PortalClient.java
- src/main/java/org/atlasapi/remotesite/btvod/portal/XmlPortalClient.java
- src/test/java/org/atlasapi/remotesite/btvod/portal/XmlPortalClientTest.java
The BT API cannot return an emptyset for a valid,
but empty, group. Therefore we will catch that case
and interpret any 404 as an empty group.
> Treat a 404 as no content

- src/main/java/org/atlasapi/remotesite/ContentMerger.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/LocalOrRemoteNitroFetcher.java
- src/main/java/org/atlasapi/remotesite/btfeatured/BtFeaturedContentUpdater.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodBrandWriter.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodItemWriter.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodSeriesWriter.java
- src/main/java/org/atlasapi/remotesite/five/FiveBrandProcessor.java
- src/main/java/org/atlasapi/remotesite/getty/DefaultGettyDataHandler.java
- src/main/java/org/atlasapi/remotesite/itv/whatson/ItvWhatsOnEntryProcessor.java
- src/main/java/org/atlasapi/remotesite/knowledgemotion/DefaultKnowledgeMotionDataRowHandler.java
- src/main/java/org/atlasapi/remotesite/lovefilm/DefaultLoveFilmDataRowHandler.java
- src/main/java/org/atlasapi/remotesite/netflix/DefaultNetflixXmlElementHandler.java
- src/main/java/org/atlasapi/remotesite/rte/RteModule.java
- src/main/java/org/atlasapi/remotesite/talktalk/ContentUpdatingTalkTalkVodEntityProcessor.java
- src/main/java/org/atlasapi/remotesite/youview/DefaultYouViewElementProcessor.java
- src/main/java/org/atlasapi/remotesite/youview/DefaultYouViewXmlElementHandler.java
- src/main/java/org/atlasapi/remotesite/youview/YouViewContentExtractor.java
- src/test/java/org/atlasapi/remotesite/ContentMergerTest.java
- src/test/java/org/atlasapi/remotesite/rte/RteFeedProcessorTest.java
- src/test/java/org/atlasapi/remotesite/youview/DefaultYouViewElementProcessorTest.java
This reduces, greatly, the number of items where they're
repeated on regional variants.
> Store youview items by pcrid, where available

- src/main/java/org/atlasapi/remotesite/youview/YouViewEquivalenceBreaker.java
- src/main/java/org/atlasapi/remotesite/youview/YouViewModule.java
- src/test/java/org/atlasapi/remotesite/youview/YouViewEquivalenceBreakerTest.java
This should see a much better throughput, as we'll reduce the number of writes greatly. We're now
writing one entry per item in the equivalent set, rather than detaching each separately, which each would cause one write per item in the set.
> Use LookupEntryStore directly to orphan items

- src/main/java/org/atlasapi/remotesite/opta/events/OptaEventsUtility.java
- src/test/java/org/atlasapi/remotesite/opta/events/sports/OptaEventsUtilityTest.java
This makes it consistent with the former feed, where there
was not a leading t.
> Remove leading character from opta ID

- src/main/java/org/atlasapi/query/v2/ScheduleController.java
- src/test/java/org/atlasapi/query/v2/ScheduleControllerTest.java
It's an error not to provide a publisher or API key to /schedule but
resulting message was "Need precedence enabled" didn't described that
very well. If neither param is supplied then "You must supply a
publisher or API key" is displayed.
If an API key without precedence is supplied without a publishers then
the original message is displayed.
> Improve ScheduleController error message when key and source missing

- src/main/java/org/atlasapi/remotesite/bt/events/BtEventsDataHandler.java
- src/main/java/org/atlasapi/remotesite/bt/events/BtEventsUtility.java
- src/main/java/org/atlasapi/remotesite/events/DataHandler.java
- src/main/java/org/atlasapi/remotesite/events/EventParsingDataHandler.java
- src/main/java/org/atlasapi/remotesite/events/EventsIngestTask.java
- src/main/java/org/atlasapi/remotesite/events/EventsUtility.java
- src/main/java/org/atlasapi/remotesite/opta/events/OptaEventsModule.java
- src/main/java/org/atlasapi/remotesite/opta/events/OptaEventsUtility.java
- src/main/java/org/atlasapi/remotesite/opta/events/OptaSportConfiguration.java
- src/main/java/org/atlasapi/remotesite/opta/events/sports/OptaSportsDataHandler.java
- src/main/resources/config/environment.properties
- src/test/java/org/atlasapi/remotesite/events/EventParsingDataHandlerTest.java
- src/test/java/org/atlasapi/remotesite/opta/events/sports/OptaEventsUtilityTest.java
- src/test/java/org/atlasapi/remotesite/opta/events/sports/OptaSportsDataHandlerTest.java
The original Opta feed that was used was had IDs that
differ from the new one we're using. We therefore had
had to remove the prefix 't'. However, it transpired
that we should only do this removal for rugby, since
for other sports the IDs were consistent between the
two feeds.
> Make Opta ID parsing sport-specific

- src/main/java/org/atlasapi/remotesite/bbc/nitro/BbcNitroModule.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/DayRangeChannelDaySupplier.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroClipsAdapter.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroContentAdapter.java
- src/main/resources/config/environment.properties
Instead of requesting all programmes/availabilities/versions
for a schedule day in one go, batch them to improve throughput
> Batch and parallelise requestes to Nitro

- src/main/java/org/atlasapi/query/v2/TaskController.java
This avoids doing expensive regexp queries
> Temporary fix to prefix content uri queries with nitro uri

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/EquivTaskModule.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodBrandWriter.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodDescribedFieldsExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodItemWriter.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodModule.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodMpxImageExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodSeriesWriter.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodUpdater.java
- src/main/java/org/atlasapi/remotesite/btvod/DerivingFromItemBrandImageExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/ImageExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/model/BtVodPlproductImages.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodBrandWriterTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodItemWriterTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodMpxImageExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodSeriesWriterTest.java
- src/test/java/org/atlasapi/remotesite/btvod/DerivingFromItemBrandImageExtractorTest.java
- Add new source, to ingest low-res images into for testing
without affecting users of the existing source
- Derive brand image from the image of the first episode
in the feed, according to editorial ordering
> Ingest images from MPX

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/results/combining/RequiredScoreFilteringCombiner.java
- src/main/java/org/atlasapi/equiv/scorers/SequenceItemScorer.java
Previously anything with a null title score was filtered. This
causes problems if the titles are of a different format, e.g.
one is "Episode 1", the other the editorial title.
> TVE equiv should allow either a sequence or title score

- src/main/java/org/atlasapi/equiv/scorers/ContainerHierarchyMatchingScorer.java
- src/test/java/org/atlasapi/equiv/scorers/ContainerHierarchyMatchingScorerTest.java
If hierarchies differ by too much, score according
to mismatchScore rather than giving a null score.
> Penalise hierarchy mismatches

- src/main/java/org/atlasapi/equiv/scorers/ContainerHierarchyMatchingScorer.java
- src/test/java/org/atlasapi/equiv/scorers/ContainerHierarchyMatchingScorerTest.java
They were being counted twice, both in the mismatch
count and also in the difference in number of elements.
> Don't double count series that are skipped

- src/main/java/org/atlasapi/remotesite/btvod/AbstractBtVodSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodItemExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodSynthesizedSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodUpdater.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodItemExtractorTest.java
The box-set tag was being applied to brands through the
erroneous creation of an item from the season record in MPX.
When that was removed, the box-set tag wasn't applied to brands,
since the tag is only derived from the season record.
We now propagate the same set of tags from a series to a brand
as we do from an episode to its parents.
> Propagate tags from series to brands

- src/main/java/org/atlasapi/remotesite/ContentMerger.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractor.java
- src/test/java/org/atlasapi/remotesite/ContentMergerTest.java
- src/test/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractorTest.java
This is ingested into a release date, of type first broadcast. We will use this as a sort order for upload to YouView where there is no position provided by Nitro.
`ContentMerger` now merges release dates, too.
> Ingest release date from Nitro

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/scorers/ContainerHierarchyMatchingScorer.java
- src/main/java/org/atlasapi/equiv/scorers/SubscriptionCatchupBrandDetector.java
- src/test/java/org/atlasapi/equiv/scorers/ContainerHierarchyMatchingScorerTest.java
- src/test/java/org/atlasapi/equiv/scorers/SubscriptionCatchupBrandDetectorTest.java
These brands only have a few episodes available, so hierarchy
matching will score badly, since hierarchies will differ
greatly from equivalence candidates with fuller catalogues
(such as broadcast data sources)
> Disable hierarchy scoring for subscription catchup brands

- src/main/java/org/atlasapi/remotesite/btvod/AbstractBtVodSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodDescribedFieldsExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodItemExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodSynthesizedSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/DedupedDescriptionAndImageUpdater.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/DedupedDescriptionAndImageUpdaterTest.java
- The existing logic mistakenly selectes images and descriptions from
the first MPX row to be processed and ignored all those that were
deduped into it
> Fix bug where images/descriptions only came from first row

- src/main/java/org/atlasapi/remotesite/btvod/BtVodItemExtractor.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodItemExtractorTest.java
Only the merge victim's topics are currently stored; this change
ensure that topics across all variants of an item are stored.
> Copy topics from variants of VoD items

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/scorers/SequenceItemScorer.java
- src/test/java/org/atlasapi/equiv/scorers/SequenceItemScorerTest.java
Hierarchies are known to mismatch between BT and PA,
so we'll ascribe less value to them.
> Downweigh sequence scoring for BT VOD

- src/main/java/org/atlasapi/equiv/handlers/MessageQueueingResultHandler.java
- src/test/java/org/atlasapi/equiv/handlers/MessageQueueingResultHandlerTest.java
- src/test/java/org/atlasapi/remotesite/pa/PaBaseProgrammeUpdaterTest.java
- Equivalence assertion messages are not idempotent so we need to
guarantee message ordering by ensuring messages about the same
resource are on the same partition
> Set partition key for equivalence assertion messages

- src/main/java/org/atlasapi/equiv/generators/ContainerCandidatesContainerEquivalenceGenerator.java
We should only consider series of equivalated brands as candidates for matching, not the series of the candidates of the brand match. For example:
```
Ba-------Bb       Bc
|        |       |
Sa       Sb       Sc
```
If Bc was a equivalence candidate in the match of Ba, but Bb was chosen, then only the series of Bb should be candidates for matching to Sa. Previously this was not the case, and we would consider series of Bb and Bc.
> Use equivalated brands for series match candidates

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/results/extractors/PercentThresholdAboveNextBestMatchEquivalenceExtractor.java
- src/test/java/org/atlasapi/equiv/results/extractors/PercentThresholdAboveNextBestMatchEquivalenceExtractorTest.java
Previously, we took the sum of all candidates with a threshold
for the strongest candidate to beat based on that. However,
with many candidates this strategy falls down. Instead, we'll
look at the second strongest candidate and ensure the
strongest candidate is at least n times greater than it.
We're only including this as part of BT VOD equivalence
in the first instance, but may roll out more widely if it
proves a good general strategy.
> Only take into account next best candidate

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/generators/ContentTitleScorer.java
- src/main/java/org/atlasapi/equiv/generators/TitleSearchGenerator.java
- src/test/java/org/atlasapi/equiv/generators/ContentTitleScorerTest.java
- src/test/java/org/atlasapi/equiv/generators/TitleSearchGeneratorTest.java
Where a dataset may be incomplete, we shouldn't fuzzy
match on titles, since there may not be a match to win
out against a partial title match.
> Require exact title match on vod content brands

- src/main/java/org/atlasapi/remotesite/btvod/BtVodModule.java
A CP tag on an item or season needs to be present on a
brand so the item is navigable from a brand list.
Corrects a problem with AMC content, where some wasn't
being surfaced.
> Propagate CP tags up hierarchies

- src/main/java/org/atlasapi/output/simple/EventModelSimplifier.java
- The write path permits events that have no startTime, endTime or
venue. The read path should be able to handle the same.
> Prevent event simplification from throwing NPE

- src/main/java/org/atlasapi/remotesite/bbc/nitro/PidUpdateController.java
Episodes from a "top level series" might not have a brand container and have a Series set as their container. The brand update logic was relying on an Episode's container being a Brand.
> Guard against missing brand in Nitro force update controller.

- src/main/java/org/atlasapi/equiv/EquivModule.java
BUGFIX: A container shouldn't require a child item
equivalence score to be matched; instead, they should
require a title score.
There may be no child matches, but if there is a title
match thay should suffice. In cases where there
is no schedule matching, requiring a child match before
a container match is allowed leads to a circular
dependency resulting in a failure to match ever.
> Containers must require a title score, not child score

- src/main/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorer.java
- src/test/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorerTest.java
A '/' is used as a delimeter around back-to-back titles.
In some cases there are surrounding spaces, in others not.
These are now normalized, to not having spaces, to allow
a positive match.
An attempt was made to remove all spacing as part of this
change; however, abbreviations for sports teams makes use
of the position of spaces to allow abbrevations to match
full names, so spaces need to be considered to avoid
mis-matches.
> Normalize spacing around back-to-back delimeters

- src/main/java/org/atlasapi/remotesite/ContentMerger.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractor.java
The latter was deprecated and removed. We must also support switching from type Item to type Film, since there will be a number of Items becoming Films.
> Move to programme_formats from formats

- src/main/java/org/atlasapi/equiv/results/persistence/FileEquivalenceResultStore.java
Putting all equivalence results in the same directory causes
fun and games with lots of files in the directory. Instead, we
will hash the filename and create a two-directory deep
structure to split the files up.
We'll attempt to find a results file from both the base
directory and the new hash structure, so that old results can
still be retrieved.
> Split equivalence result files into multiple directories

- src/main/java/org/atlasapi/remotesite/btvod/AbstractBtVodSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodBrandExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodModule.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodSynthesizedSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodTagMap.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodUpdater.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodBrandExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodSynthesizedSeriesExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodTagMapTest.java
Added BT genre mapping to MB tags and storing them as TopicRefs.
Added tests.
In BtVodModule changed the TopicWriter to TopicStore, this was done because I need to do a lookup for the Topic to make use of existing topic when creating and storing MB tag as a TopicRef. Also TopicStore extends TopicWriter and TopicLookupResolver, where TopicLookupResolver can be used for Topic lookup.
> Added BT genre mapping to MB tags and storing them as TopicRefs.

- src/main/java/org/atlasapi/remotesite/btvod/HierarchyDescriptionAndImageUpdater.java
- src/test/java/org/atlasapi/remotesite/btvod/HierarchyDescriptionAndImageUpdaterTest.java
- We may see the same source multiple times as different BT VoD entries
get deduped in it and each time which images and descriptions have been
kept as part of the deduping process may have changed so we must
update every time we see a metadata source of equal priority as the
existing one because it will be the same one with potentially more up
to date metadata
> Update images and description from source of equal priority as existing

- src/main/java/org/atlasapi/remotesite/pa/PaModule.java
- src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
- src/test/java/org/atlasapi/remotesite/pa/PaBaseProgrammeUpdaterTest.java
- Several beans require PaTagMap to be passed in a constructor
parameter. However, PaTagMap was being instantiated in PostConstruct,
but PostConstruct is called after non-lazy beans are created so at
the time of bean creation it is null
- Added defensive null checking in PaProgrammeProcessor constructor
- Added logging to PaProgrammeProcessor
- Fixed broken tests in PaBaseProgrammeUpdaterTest that were failing
due to trying to write into a file system directory that does not
exist on developer systems
> Fix NPE in PaProgrammeProcessor

- src/main/java/org/atlasapi/remotesite/pa/PaModule.java
- src/main/java/org/atlasapi/remotesite/pa/PaRecentUpdater.java
- This is needed in case a file ingest fails, but mistakenly reports
itself as having successfully finished
> Create PA recent updater to re-ingest even successfully processed files

- src/main/java/org/atlasapi/remotesite/pa/PaModule.java
- src/main/java/org/atlasapi/remotesite/pa/PaSingleDateUpdater.java
- src/main/java/org/atlasapi/remotesite/pa/PaSingleDateUpdatingController.java
- PA updates are potentially quite expensive so the update controller
will only have one thread to process multiple requests any incoming
requests
> Update pa update controller to use POST and to be single-threaded

- src/main/java/org/atlasapi/equiv/update/tasks/ScheduleEquivalenceUpdateTask.java
Instead of running forwards from t to t+n, we will run from t+n
backwards to t. This ensure we don't starve the far end of the
schedule where equivalence may never have been run, in the case
jobs are interrupted.
> Reverse schedule equivalence job

- src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
A bug was introduced whereby the channel wasn't being
appended to the close item uri, which meant a new close item
was being created on every ingest of the close, rather than
amending the existing one, leading to broadcasts being lost.
> Resolve channel-specific close item

- src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
- src/main/resources/TVListings.dtd
- src/test/java/org/atlasapi/remotesite/pa/PaProgrammeProcessorTest.java
Revised repeat means that a broadcast is a repeat, but has
been edited since the original broadcast. In Atlas we do not
make such a distinction, we coalesce PA's repeat and revised
repeat flag into a single field.
> Ingest revised repeat flag from PA

- src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
Instead of using rt_filmnumber, which isn't solely
set on films, we'll use the film flag as provided by PA to
decide if an Item is a Film or not.
> Use PA film field to decide type of film

- src/main/java/org/atlasapi/remotesite/opta/events/OptaEventsUtility.java
Updated Opta event group titles for UEFA Champions and Europa leagues, this is done as we are currently getting the wrong titles for event groups on event queries to Atlas.
> Updated Opta event group titles for UEFA Champions and Europa leagues

- src/main/java/org/atlasapi/remotesite/btvod/BtVodBrandExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodBrandProvider.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodDescribedFieldsExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodItemExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodModule.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodSeriesProvider.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodSynthesizedSeriesExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodUpdater.java
- src/main/java/org/atlasapi/remotesite/btvod/HierarchyDescriptionAndImageUpdater.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodBrandExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodBrandProviderTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodDescribedFieldsExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodExplicitSeriesExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodItemExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodSeriesProviderTest.java
- src/test/java/org/atlasapi/remotesite/btvod/BtVodSynthesizedSeriesExtractorTest.java
- src/test/java/org/atlasapi/remotesite/btvod/HierarchyDescriptionAndImageUpdaterTest.java
- When synthesising brand/series added guid/id of MPX row that
created it as an alias with 'synthesised' namespace
- When updating images/descriptions from the hierarchy add alias
with the guid of the row that propagated its images/descriptions
> Update aliases for MPX ingester

- src/main/java/org/atlasapi/remotesite/bt/events/BtEventsUtility.java
- src/main/java/org/atlasapi/remotesite/events/EventsUtility.java
- src/main/java/org/atlasapi/remotesite/opta/events/OptaEventsUtility.java
- src/test/java/org/atlasapi/remotesite/events/EventsUtilityTest.java
- This is so that API users can distinguish which event group
contains the competition title by its namespace
> Change namespace for Opta competition event groups

- src/main/java/org/atlasapi/remotesite/btvod/BtVodModule.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodUpdater.java
- src/main/java/org/atlasapi/remotesite/btvod/HierarchyDescriptionAndImageUpdater.java
- src/test/java/org/atlasapi/remotesite/btvod/HierarchyDescriptionAndImageUpdaterTest.java
- The description, long description and images of a brand or series
could have come from different items so we should have separate aliases
for each
- The decision of which images and descriptions a content
should have is taken elsewhere. Therefore when an update source comes
that has the same priority as the existing source we should check the
actual metadata has changed before applying it and updating the alias
> Fix logic for MPX images and descriptions aliases

- src/main/java/org/atlasapi/remotesite/btvod/BtVodVersionsExtractor.java
- src/main/java/org/atlasapi/remotesite/btvod/model/BtVodEntry.java
Ingest rules did not correctly specify when content is available
to play. The presence of the masterAgreementServiceType:OTG is
also required (i.e. serviceType:OTG AND
masterAgreementServiceType:OTG required). This means only content
with both these tags are playable on TVE (they may still be present
in the feed though because they are playable on a STB).
> Require masterAgreementServiceType OTG

- src/main/java/org/atlasapi/equiv/scorers/TitleSubsetBroadcastItemScorer.java
- src/test/java/org/atlasapi/equiv/scorers/TitleSubsetBroadcastItemScorerTest.java
Same normalization we do for title scorer. To handle cases like Power Rangers: R.P.M. and Power Rangers RPM
> Added title transformation to the broadcast subset title scorer

- src/main/java/org/atlasapi/remotesite/youview/DefaultYouViewChannelResolver.java
- src/test/java/org/atlasapi/remotesite/youview/DefaultYouViewChannelResolverTest.java
Historically, PA don't provide YV IDs for all channels, usually radio has some missing. We add manual
override aliases for these. Sometimes PA decides to add the YV IDs, which leads to the existence of both
an override and an ingest alias on two different channel IDs.
This then causes problems with the YV channel resolver initialization, because it caches things and
these two IDs clash, which then leads to processing not starting up.
The fix is preferring the manual override even if an ingested ID is present, because we want to
keep ingesting schedule data on the same channel that we started doing it on historically. I.e.,
the override is older and therefore gets precedence.
> Make YV channel resolver prefer manual overrides

- src/main/java/org/atlasapi/equiv/EquivTaskModule.java
- src/main/java/org/atlasapi/equiv/update/tasks/ScheduleEquivalenceUpdateTask.java
- src/test/java/org/atlasapi/equiv/update/tasks/ScheduleEquivalenceUpdateTaskTest.java
The set of channels may change over the lifetime of a JVM.
Instead we'll use a Supplier<Iterable<Channel>> so they
can be recomputed when needed.
> Don't cache channels for youview equivalence

- src/main/java/org/atlasapi/remotesite/pa/PaHelper.java
- src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
- src/test/java/org/atlasapi/remotesite/pa/PaProgrammeProcessorTest.java
film number. Resolving existing content uses both URI styles to avoid
creating duplicate content. Aliases of the alternate style is added to
the content.
> Create canonical URIs for Films based on their prodId rather than RT

- src/main/java/org/atlasapi/remotesite/ContentMerger.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/ContentUpdatingNitroBroadcastHandler.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/LocalOrRemoteNitroFetcher.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/BaseNitroItemExtractor.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroAvailabilityExtractor.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractor.java
- src/test/java/org/atlasapi/remotesite/ContentMergerTest.java
In theory, these things should never just magically vanish, they should only ever be revoked. In practice,
theory and practice aren't the same, and we need to gracefully cope with this case to then propagate these
changes to our other partners. This tries to fuzzy match versions and availabilities and revokes them
if it can't find them. This aims for recall over precision, so we *might* mistakenly revoke some
availabilities when we mismatch, but we should always catch any actual deletions.
> Handle availabilities and versions disappearing in Nitro.

- pom.xml
- src/main/java/org/atlasapi/remotesite/bbc/nitro/OffScheduleContentIngestTask.java
Currently we fetch only available items, which by definition means we lag behind by some sampling
duration. Nitro has the option to query for content that will become available in the future,
so we should ingest content before it actually becomes available.
> Fetch items 12h in future for Nitro off-schedule ingest.

- src/main/java/org/atlasapi/system/HealthController.java
- This is the minimum viable test to assert the jetty is up and
serving HTTP requests
> Implement a /system/alive endpoint that always returns 200

- src/main/java/org/atlasapi/query/ProcessingTimeFilter.java
- src/main/webapp/WEB-INF/web.xml
- src/test/java/org/atlasapi/query/ProcessingTimeFilterTest.java
- This is intended to give us a measure of which requests are
intrinsically expensive by measuring the time it takes to process
them and ignoring any time waiting for a request thread to become
available
> Create filter that adds a request's processing time as a response header

- src/main/java/org/atlasapi/query/v2/ChannelController.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroChannelAdapter.java
This means
* stop ingesting media type for masterbrands, since that field is meaningless in that context
* expose the channelType field for querying via API
> Add support to query channels by their type

- src/main/java/org/atlasapi/system/ContentPurgeWebModule.java
SubstitutionTableNumberCodec by default uses the upper case alphabet
> MBST-15461: Unpublish endpoint: ID codec configuration fix

- src/main/resources/config/environment.properties
- Change Premier League, Scottish Premier League, Bundesliga to 2016
season. Champions League, Europa League and FA Cup do not yet have
2016 data available so they will be updated later
> Change Opta ingester to 2016 season

- src/main/java/org/atlasapi/remotesite/btvod/BtVodModule.java
- src/main/java/org/atlasapi/remotesite/btvod/BtVodUpdater.java
- src/main/resources/config/environment.properties
- This is done because the new content feed for the Vol-E environment
has a different name than one in the production environment that we
had hardcoded before
- Also remove unused `newFeedContentMatchingPredicate` from BtVodUpdater
> Externalise to config the name of MPX feed for new content

- src/main/java/org/atlasapi/equiv/generators/BroadcastMatchingItemEquivalenceGenerator.java
to allow match on endtime more flexibly
> easing rules for matching on broadcast

- src/main/java/org/atlasapi/remotesite/bbc/nitro/GlycerinNitroChannelAdapter.java
- Even though channel keys are deprecated they are still required as
parts of the code assume a channel will always have a key and can
NPE if it's missing
> Add key to Nitro channels

- src/main/java/org/atlasapi/input/ChannelModelTransformer.java
- src/test/java/org/atlasapi/input/ChannelModelTransformerTest.java
because key is compulsory field in some part of the system
> When desserialing channel we set key from uri

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/scorers/DescriptionTitleMatchingScorer.java
- src/test/java/org/atlasapi/equiv/scorers/DescriptionTitleMatchingScorerTest.java
- Created equivalence scorer for matching title and description
keywords. This helps with some content that has a description but
no title or vv.
> Add a scorer for matching title and description

- src/main/java/org/atlasapi/query/QueryWebModule.java
- src/main/java/org/atlasapi/query/v2/ContentWriteController.java
- src/main/java/org/atlasapi/query/v2/QueryController.java
- src/test/java/org/atlasapi/query/v2/ContentWriteControllerTest.java
If a DELETE request is accepted with a valid API key then the ID / URI parameter from the request is used to resolve a piece of content. If the API key has write permissions for that contents publisher then it is flagged as unpublished.
> Add support unpublishing content by id/uri

- src/main/java/org/atlasapi/query/content/ContentWriteExecutor.java
- The write executor was not updating the actively published flag in
the existing content which means if the existing content was
unpublished it was impossible to re-publish it via the API
> When writing new content set actively published

- src/main/java/org/atlasapi/query/QueryExecutorModule.java
- src/main/java/org/atlasapi/query/content/ContentWriteExecutor.java
- src/main/java/org/atlasapi/query/content/merge/BroadcastMerger.java
- src/main/java/org/atlasapi/query/content/merge/package-info.java
- src/main/java/org/atlasapi/query/v2/ContentWriteController.java
- src/test/java/org/atlasapi/query/content/merge/BroadcastMergerTest.java
- src/test/java/org/atlasapi/query/v2/ContentWriteControllerTest.java
- src/test/java/org/atlasapi/query/worker/ContentWriteWorkerTest.java
- The broadcast assertions are effectively a promise made by the
writer that if any broadcasts existed in the asserted
channel/dateTime ranges for the written item then these broadcasts
would have been provided in this write. Therefore Atlas can use
these assertions to remove any existing broadcast in the given
range and replace it with the ones provided
- The existing behaviour of removing all existing broadcasts and
replacing them with the new ones is preserved if no broadcast
assertions are provided
> Add support for broadcastAssertions request parameter when writing

- src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
- This was not previously supported, but the ingester is already
converting episodes to films where needed so functionally this
should not be any different
- Also `Item.copyTo` was set to `protected`, which meant that anyone
calling `Item.copyTo` from outside the Item class hierarchy was
effectively calling `Content.copyTo` which `Item` inherits and is
thus missing some fields. Changing `Item.copyTo` to public will
affect the `ContentMerger` class as well as the merging logic in
the RT ingester that use this, but this should be the correct
behaviour and it's likely that those parts of the codebase never
intended to rely on this behaviour and instead didn't realise that
some fields were being missed
> Add support for changing episodes to items in the PA ingester

- src/main/java/org/atlasapi/remotesite/pa/PaBaseProgrammeUpdater.java
- src/main/java/org/atlasapi/remotesite/pa/PaCompleteUpdater.java
- src/main/java/org/atlasapi/remotesite/pa/PaModule.java
- src/main/java/org/atlasapi/remotesite/pa/PaRecentUpdater.java
- src/main/java/org/atlasapi/remotesite/pa/PaSingleDateUpdater.java
- src/test/java/org/atlasapi/remotesite/pa/PaBaseProgrammeUpdaterTest.java
Prior to this change a bootstrap would only process unprocessed files
rather than the desired behavior of of re processing the most recent.
> Fix bug where PA bootstrap would not re-ingest any files

- src/main/resources/config/environments/prod.properties
- This caused app servers to start running equivalence jobs because
equiv updaters used to be enabled by default
> Ensure equivalence updaters are only explicitly enabled

- src/main/java/org/atlasapi/query/QueryWebModule.java
This import coupled with default config causes app servers to enable
tasks that only the processing servers should be running.
> Remove EquivTaskModule import from QueryWebModule

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/equiv/results/combining/NullScoreAwareAveragingCombiner.java
- src/main/java/org/atlasapi/equiv/update/ContentEquivalenceUpdater.java
- src/test/java/org/atlasapi/equiv/results/combining/NullScoreAwareAveragingCombinerTest.java
flag can be set to change logic in combiner to set score to 0 if all scorers returned null
ebs sport content registered to use this flag
> add flag to reset the score on content with only null results for ebs

- src/main/java/org/atlasapi/equiv/EquivModule.java
This will mean that nothing can equivalate this publishers content but
content from this publisher can still equivalate to other things.
> Remove c4 press from acceptable publishers

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfUpdateTask.java
Intended behaviour is now:
* RT Upcoming to only equivalate to Amazon Unbox content
* Nothing can equivalate to RT Upcoming.
> Remove RT Upcoming from general equivalence

- src/main/java/org/atlasapi/equiv/EquivModule.java
- src/main/java/org/atlasapi/remotesite/itunes/epf/ItunesEpfUpdateTask.java
Intended behaviour is now:
RT Upcoming to only equivalate to Amazon Unbox content
Nothing can equivalate to RT Upcoming.
j
> Remove rt upcoming from normal equivalence

- src/main/java/org/atlasapi/equiv/generators/BroadcastMatchingItemEquivalenceGenerator.java
- src/main/java/org/atlasapi/equiv/generators/EquivalenceGenerator.java
- src/main/java/org/atlasapi/equiv/generators/FilmEquivalenceGenerator.java
- src/main/java/org/atlasapi/equiv/generators/TitleSearchGenerator.java
- src/main/java/org/atlasapi/equiv/generators/metadata/EquivalenceGeneratorMetadata.java
- src/main/java/org/atlasapi/equiv/generators/metadata/GenericEquivalenceGeneratorMetadata.java
- src/main/java/org/atlasapi/equiv/generators/metadata/SourceLimitedEquivalenceGeneratorMetadata.java
- src/main/java/org/atlasapi/equiv/update/ContentEquivalenceUpdater.java
- src/main/java/org/atlasapi/equiv/update/EquivalenceUpdater.java
- src/main/java/org/atlasapi/equiv/update/MultipleSourceEquivalenceUpdater.java
- src/main/java/org/atlasapi/equiv/update/NullEquivalenceUpdater.java
- src/main/java/org/atlasapi/equiv/update/RootEquivalenceUpdater.java
- src/main/java/org/atlasapi/equiv/update/SourceSpecificEquivalenceUpdater.java
- src/main/java/org/atlasapi/equiv/update/metadata/ContentEquivalenceUpdaterMetadata.java
- src/main/java/org/atlasapi/equiv/update/www/ContentEquivalenceUpdateController.java
- This will show which sources we equivalate to
- Also add support in equivalence configuration endpoint to only show
equivalence for a single publisher
- Add sorting by publisher to make the output more readable
> Add equivalence generator metadata

- src/main/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorer.java
- src/test/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorerTest.java
examples were found where titles separated by v were not matching the same titles separated by vs
this fixes that problem
> adding normalisation logic for titles that looks for variation on vs

- src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
- This is to allow equivalence between films in the two datasets that
do not exist in the PA dataset
> Add Amazon Unbox to sources RT can equiv to

- src/main/java/org/atlasapi/remotesite/pa/PaHelper.java
- src/test/java/org/atlasapi/remotesite/pa/archives/PaArchivesProgExtractorTest.java
- Clients are using the legacy style so we need to revert. Also
removing the new style RT film alias to avoid having duplicate data
> Revert to using the old style RT film ID

- src/main/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorer.java
- src/test/java/org/atlasapi/equiv/scorers/TitleMatchingItemScorerTest.java
Edge case 1 - title starts with more than one ':' throwing OOB
Edge case 2 - title starts with a number followed by a colon and matches a regex throwing OOB
Due to these changes, titles with a leading ':' may be less likely to get a partial match, but these should be rare anyway. These changes are reflected in the test alterations
> fix two edge cases in equivalence scorer

- src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/container/RtUpcomingContainerUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/RtUpcomingItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/types/ContainerEquivalenceUpdaterType.java
The same updater provider is going to be used for top level containers and non top level containers for RTU, hence some renaming
TitleSearchGenerator is now used for Items as they have no broadcasts to generate from
> reconfigure RT upcoming equivalence

- src/main/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentExtractor.java
- src/test/java/org/atlasapi/remotesite/amazonunbox/AmazonUnboxContentExtractorTest.java
We found a series with an image in images with a null uri and it caused issues
This should prevent this from happening in the future
> fix bug where null uri gets passed to images which then does not resolve

- src/main/java/org/atlasapi/remotesite/pa/channels/PaChannelDataHandler.java
- src/test/java/org/atlasapi/remotesite/pa/channels/PaChannelDataHandlerTest.java
Existing images that were ingested without dates persisted and caused issues
as there were duplicate themes for valid dates. This should clean those up
while preserving the logic.
> Sanitise existing channel images

- src/main/java/org/atlasapi/remotesite/bt/channels/AbstractBtChannelGroupSaver.java
When the ingest run and found a channel it could not process, the whole
job would fail. This logs the exception and should continue to process.
> Fix failing on first exception

- src/main/java/org/atlasapi/equiv/scorers/TitleSubsetBroadcastItemScorer.java
- src/test/java/org/atlasapi/equiv/scorers/TitleSubsetBroadcastItemScorerTest.java
If there is a name consisting of purely common words, or stripped
characters then titles won't match. In this case if there's an exact
match it would make sense to return a positive score.
This scorer also originally replaced an exact match scorer, so it
simply makes it a complete replacement/improvement of the old scorer.
> Add an exact match check to equiv TitleSubset scorer.

- src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BarbItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/TxlogsItemUpdaterProvider.java
When/if equiv writing is updated to properly cope with
unidirectional equiv then these changes can be
undone.
> Made BARB equiv bidirectional as mentioned in ENG-246

- src/main/java/org/atlasapi/equiv/generators/BarbAliasEquivalenceGeneratorAndScorer.java
> Accept gb:barb:contentid aliases when generating candidates 

- src/main/java/org/atlasapi/equiv/update/updaters/configuration/DefaultConfiguration.java
This is to prevent accidentally adding new sources to the model which
can then be equived to indavertently. Instead adding a new source
will now require updating this set with the new source if it is
desired for any equivalence already using the set to include it.
> Hardcode set of target sources for equiv

- src/main/java/org/atlasapi/equiv/generators/BarbAliasEquivalenceGeneratorAndScorer.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BarbItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BarbXItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/TxlogsItemUpdaterProvider.java
- src/test/java/org/atlasapi/equiv/generators/BarbAliasEquivalenceGeneratorAndScorerTest.java
Sky has bad data so if an originating owner broadcaster exists and isnt sky, don't use the parent bcid aliases to generate equiv candidates.
https://metabroadcast.atlassian.net/browse/ENG-267
> Sky bcid equiv

- src/main/java/org/atlasapi/query/QueryExecutorModule.java
- src/main/java/org/atlasapi/query/content/ContentWriteExecutor.java
- src/main/java/org/atlasapi/remotesite/channel4/pmlsd/epg/ScheduleResolverBroadcastTrimmer.java
Problem is that broadcast amendments done thru owl-api (eg. stuff like txlogs)
make the broadcast that was already there stick around on that piece of content.
This change makes it so that they get trimmed (ie. marked as unpublished).
https://metabroadcast.atlassian.net/browse/ENG-226
> trim broadcasts in owl-api on amendments

- pom.xml
- src/main/java/org/atlasapi/equiv/EquivTaskModule.java
- src/main/java/org/atlasapi/equiv/update/tasks/ContentEquivalenceUpdateTask.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/LastUpdatedSettingContentWriter.java
- src/test/java/org/atlasapi/equiv/update/tasks/ContentEquivalenceUpdateTaskTest.java
This is part of a workaround to prevent MongoCursorNotFoundException which stopped equiv from properly rerunning on all content from a publisher. The change is to use a List of content uris instead of an Iterator of Content, and resolving the content afterwards.
https://metabroadcast.atlassian.net/browse/ENG-316
> Avoid cursor timeout

- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/BaseNitroItemExtractor.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroBroadcastExtractor.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/extract/NitroEpisodeExtractor.java
This is for work for BARB relating to equivalence and filling
in episode and original version PIDs in CCIDSTxLogs.
More information can be found in JIRA ENG-339.
* Refactored some existing logic with version pids and
version crids in NitroEpisodeExtractor into
BaseNitroItemExtractor.
> Ingest original version pids and actual tx start and end times

- src/main/java/org/atlasapi/equiv/generators/barb/BarbBbcActualTransmissionItemEquivalenceGeneratorAndScorer.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BbcTxlogsItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BarbBbcBroadcastItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/types/ItemEquivalenceUpdaterType.java
- src/test/java/org/atlasapi/equiv/generators/barb/BarbBbcActualTransmissionItemEquivalenceGeneratorAndScorerTest.java
Based off feedback from BBC.
* Relaxed the regular broadcast equiv flexibility from
5mins to 10mins
* For BBC Two Wales and Northern Ireland when checking
actual transmission times only check the actual
transmission start time since Nitro is generally
missing the actual transmission end time.
> Improvements to previous equiv work for Nitro<->Txlogs

- src/main/java/org/atlasapi/query/content/ContentWriteExecutor.java
- src/main/java/org/atlasapi/query/v2/ContentWriteController.java
- src/main/java/org/atlasapi/query/v2/QueryController.java
ENG-282 contains the context but is to allow
for editors to explicitly equiv brands together
in order to move away from the frankly terrible
automatic brand equiv logic that happens at the
moment between most major broadcasters sources.
* Endpoint to explicitly equiv two pieces of content
* Endpoint to remove explicit equiv between two pieces of content
* Endpoint to update explicit equiv on a single piece of content
This endpoint is not needed but added due to there being a potential
need for it based on previous experience. It was also an initial
implementation for the above before deciding against using it.
Since it does not update the content record explicit equivalence
lists of other content it is explicitly equiving to it may cause
undesirable behaviour when updating explicit …
> Api endpoints to update explicit equiv

- src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
This is being replaced by editors explicitly equiving
brands since the existing equiv incorrectly equivs
brands sometimes just because their titles are
the same.
This may affect series and episode level equiv
since the existing ContainerCandidates generators
may now need to use the lookup entry explicit
equivs in addition to the equivalence summary
store.
> Removed top level container equiv for BARB CMS sources

- src/main/java/org/atlasapi/equiv/update/ContentEquivalenceResultUpdater.java
- src/main/java/org/atlasapi/equiv/update/ContentEquivalenceUpdater.java
- src/main/java/org/atlasapi/equiv/update/metadata/EquivToTelescopeComponent.java
Some ids were being encoded with uppercase encoding, this is now changed to use lowercase encoding. Also, some ids were not being encoded at all, but are now encoded correctly using the lowercase codec.
> Eng 241 - Fixed incorrect ids in equiv

- src/main/java/org/atlasapi/equiv/generators/barb/BarbBbcActualTransmissionItemEquivalenceGeneratorAndScorer.java
- src/main/java/org/atlasapi/equiv/generators/barb/BarbBroadcastMatchingItemEquivalenceGeneratorAndScorer.java
- src/main/java/org/atlasapi/equiv/generators/barb/utils/BarbGeneratorUtils.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BbcTxlogsItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BarbBbcBroadcastItemUpdaterProvider.java
This is to prevent short children shows being shown back-to-back
causing equiv issues where the txlog broadcasts have shifted by
a small amount, leading to two pieces of content being deemed
valid candidates for the same broadcast slot.
This may need improvement in future but for now this is to
prevent bad equiv even at the cost of no equiv.
> 5min min broadcast filter to regular nitro<->txlog broadcast equiv

- src/main/java/org/atlasapi/equiv/generators/barb/BarbBroadcastMatchingItemEquivalenceGeneratorAndScorer.java
- src/main/java/org/atlasapi/equiv/results/description/NopDescription.java
- src/main/java/org/atlasapi/equiv/scorers/barb/BarbTitleMatchingItemScorer.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/BbcTxlogsItemUpdaterProvider.java
- src/main/java/org/atlasapi/equiv/update/updaters/providers/item/barb/BarbBbcBroadcastItemUpdaterProvider.java
- src/test/java/org/atlasapi/equiv/generators/barb/BarbBroadcastMatchingItemEquivalenceGeneratorAndScorerTest.java
- src/test/java/org/atlasapi/equiv/scorers/BarbTitleMatchingItemScorerTest.java
(N.B. currently only BBC Nitro <-> Txlogs uses this affected class)
The implementation looks to deal with schedule offsets between
txlogs and other schedule data, due to txlogs having actual transmission
times for their broadcasts. The code looks to identify the closest
block of broadcasts for a particular show (determined by the title
scorer) on each schedule, determine which entry within the block
the subject is, and takes the corresponding entry in the other
schedule to equiv to.
* Added container caching in BarbTitleMatchingItemScorer
to improve performance.
> Rework of Barb Broadcast Equiv

- src/main/java/org/atlasapi/equiv/generators/barb/BarbBroadcastMatchingItemEquivalenceGeneratorAndScorer.java
This is to fix an issue where multiple Nitro episodes
of different brands appeared one after the other with
similar episode titles which were just the date of transmission
or just episode numbers.
These were considered the same for block identification
since the episode titles were the same and no other check
was performed.
This logic has been changed to first compare if the brands
of the episodes are the same before checking titles.
> Change similarEpisode logic in Barb Broadcast Equiv

- pom.xml
- src/main/java/org/atlasapi/equiv/EquivTaskModule.java
- src/main/java/org/atlasapi/equiv/EquivalenceBreaker.java
- src/main/java/org/atlasapi/query/QueryWebModule.java
- src/main/java/org/atlasapi/query/v2/ContentWriteController.java
- src/main/java/org/atlasapi/remotesite/pa/PaModule.java
- src/main/java/org/atlasapi/system/ContentPurgeWebModule.java
- src/main/java/org/atlasapi/system/UnpublishContentController.java
- src/test/java/org/atlasapi/equiv/EquivalenceBreakerTest.java
- src/test/java/org/atlasapi/query/v2/ContentWriteControllerTest.java
Improve unpublishing endpoints (ENG-551)
1) the explicit equivs will now also be removed from the
lookup entry.
2) any content level equivs will be ignored when unpublishing
the content. This it to prevent content record equivs from
being written in the lookup entry (as they are considered
explicit equivs).
> Unpublish without equivalences

- src/main/java/org/atlasapi/remotesite/bbc/nitro/ContentUpdatingNitroBroadcastHandler.java
- src/main/java/org/atlasapi/remotesite/bbc/nitro/LocalOrRemoteNitroFetcher.java
The "fetched" and "existing" arguments were swapped by accident!
The result was that the existing version was always preferd, and
Containers were never updated.
> Closes MTS-665

- pom.xml
- src/main/java/org/atlasapi/deer/elasticsearch/AvailabilityQueryBuilder.java
- src/main/java/org/atlasapi/deer/elasticsearch/BroadcastQueryBuilder.java
- src/main/java/org/atlasapi/deer/elasticsearch/ContentTitleSearcher.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsAlias.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsBroadcast.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsContent.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsContentTitleSearcher.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsLocation.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsObject.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsPriceMapping.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsSchema.java
- src/main/java/org/atlasapi/deer/elasticsearch/EsTopicMapping.java
- src/main/java/org/atlasapi/deer/elasticsearch/FiltersBuilder.java
- src/main/java/org/atlasapi/deer/elasticsearch/SearchQuery.java
- src/main/java/org/atlasapi/deer/elasticsearch/SearchResults.java
- src/main/java/org/atlasapi/deer/elasticsearch/Strings.java
- src/main/java/org/atlasapi/deer/elasticsearch/TitleQueryBuilder.java
- src/main/java/org/atlasapi/deer/elasticsearch/content/Alias.java
- src/main/java/org/atlasapi/deer/elasticsearch/content/ContentType.java
- src/main/java/org/atlasapi/deer/elasticsearch/content/FieldName.java
- src/main/java/org/atlasapi/deer/elasticsearch/content/Hashable.java
- src/main/java/org/atlasapi/deer/elasticsearch/content/Id.java
- src/main/java/org/atlasapi/deer/elasticsearch/content/Specialization.java
- src/main/java/org/atlasapi/deer/elasticsearch/content/Tag.java
- src/main/java/org/atlasapi/query/SearchModule.java
- src/main/java/org/atlasapi/query/content/search/DeerSearchResolver.java
Simplified a few classes to avoid having to import
other classes that would not be needed.
Although not ideal we are copying these so that we
do not have to import deer libraries. The main reason
is that some beans in deer are being discovered
by autowiring that are causing issues sometimes when
deploying owl-api.
Since we are likely moving away from the current
elastic search anyway, a more proper solution will
likely not be worth the trouble.
> Copied classes from Deer related to Elastic Search

- pom.xml
- src/main/java/org/atlasapi/equiv/update/messagers/providers/container/StandardSeriesMessengerProvider.java
- src/main/java/org/atlasapi/equiv/update/messagers/providers/container/StandardTopLevelContainerMessengerProvider.java
- src/main/java/org/atlasapi/equiv/update/messagers/providers/item/StandardItemMessengerProvider.java
Disabled equiv messaging in messenger step of equiv framework.
It has been moved to the underlying lookup writer where it has full view of direct, explicit, and blacklisted equivs.
> Move equiv messaging to lookup writer (ENG-757)

- src/main/java/org/atlasapi/remotesite/channel4/pmlsd/C4BrandBasicDetailsExtractor.java
An investigation prompted by ENG-913 found that the C4 channel map currently contains entries for C4, M4, F4, E4, 4M, and 4S, but nothing for ALL4. This causes brands with presentation channels not in the map (e.g. Community of ALL4) to not get ingested, without manually hitting a channel 4 reingest endpoint. Adding this ignore step allows these brands to be ingested, though also adds a log line for when we come across a presentation channel that does not exist in the map.
> Ignore presentation channel when not in channel 4 channel map

- src/main/java/org/atlasapi/query/v2/ChannelController.java
Without the "." suffix the endpoint seems to automatically attempt to find a soy template which does not exist.
> Make 3.0/channels/updateImage endpoints not require soy templates

- src/main/java/org/atlasapi/query/v2/ChannelGroupController.java
- src/main/java/org/atlasapi/query/v2/ChannelGroupWriteExecutor.java
- src/test/java/org/atlasapi/query/v2/ChannelGroupWriteExecutorTest.java
Existing logic did not appear to accurately deal with updating numberings on channels which were already part of the channel group being updated, and had to update every channel in the channel group since the initial channel group before the channel update step removed all numberings.
> Improve channel group api write logic

- src/main/java/org/atlasapi/equiv/update/updaters/configuration/UpdaterConfigurationRegistry.java
Move pa and rt item equivalence to standard_item updater type, since items from PA were not scoring high enough (4+) to get matched correctly.
> Fix c4pmlsd equivalence configuration

- src/main/java/org/atlasapi/remotesite/pa/data/DefaultPaProgrammeDataStore.java
Instead of silently failing if an IOException is encountered during copying we will simply kill the process and have it restart.
Also removed an attempt to load a file that no longer exists in the codebase.
> Ensure dtd files are loaded for PA ingest

- src/main/java/org/atlasapi/remotesite/youview/YouViewContentExtractor.java
There was a deprecated check which took the service id
from the broadcast object and ensured it is present
in the channels cast (for yv schedule ingest).
This was erroring once the switch of youview ids from
numbers to uuid's. The check was unnecessary so
so it was simply removed, and getServiceId now returns string.
> Fix youview schedule ingest to work with new UUID's

- pom.xml
* Bump jetty to the version being used before it was lowered in a recent commit.
* Isolate guava dependency to help avoid incorrect version being used.
* Upgraded log4j dependency
> Bump jetty

- src/main/java/org/atlasapi/input/BroadcastModelTransformer.java
The premiere field was not getting saved when writing content with the owl client
> Adds a premiere value in the complexifier

- src/main/java/org/atlasapi/remotesite/pa/PaHelper.java
- src/main/java/org/atlasapi/remotesite/pa/PaProgrammeProcessor.java
We want the new pa api data to equiv to the file-based pa
data based on pa id, but for some reason we were never
ingesting pa season ids. Relates to eng-979.
> Ingest pa season id as alias under series.

- src/main/java/org/atlasapi/input/BrandModelTransformer.java
- src/main/java/org/atlasapi/input/ChannelModelTransformer.java
- src/main/java/org/atlasapi/input/ClipModelTransformer.java
- src/main/java/org/atlasapi/input/ContentModelTransformer.java
- src/main/java/org/atlasapi/input/DescribedModelTransformer.java
- src/main/java/org/atlasapi/input/ImageModelTransformer.java
- src/main/java/org/atlasapi/input/ItemModelTransformer.java
- src/main/java/org/atlasapi/input/PersonModelTransformer.java
- src/main/java/org/atlasapi/input/SeriesModelTransformer.java
- src/main/java/org/atlasapi/query/QueryExecutorModule.java
- src/main/java/org/atlasapi/query/QueryWebModule.java
- src/main/java/org/atlasapi/remotesite/barb/channels/BarbChannelsModule.java
- src/test/java/org/atlasapi/input/ChannelModelTransformerTest.java
- src/test/java/org/atlasapi/input/ImageModelTransformerTest.java
- src/test/java/org/atlasapi/input/ItemModelTransformerTest.java
- src/test/java/org/atlasapi/remotesite/barb/channels/BarbStringToChannelTransformerTest.java
For some unknown reason, the described model used its own (poor)
transformer logic, instead of using the more feature complete
ImageModelTransformer. This seeks to both consolidate all transformers
to use the ImageModelTransformer to complexify images, and also make
the ImageModelTransformer also complexify the Type field of Image.
This relates the new ingest-pa project (eng-989)
> Fixes content images transformer + consolidates image transformer usage
